mod 'boxen', '3.6.2',    :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.1.0',   :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'homebrew', '1.9.3', :github_tarball => 'boxen/puppet-homebrew'
